export const USER_SIGNUP_START = 'USER_SIGNUP_START';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR';
export const USER_SIGNUP_UPDATE_PROPS = 'USER_SIGNUP_UPDATE_PROPS';

export const USER_SIGNUP_CONF_START = 'USER_SIGNUP_CONF_START';
export const USER_SIGNUP_CONF_SUCCESS = 'USER_SIGNUP_CONF_SUCCESS';
export const USER_SIGNUP_CONF_ERROR = 'USER_SIGNUP_CONF_ERROR';
export const USER_SIGNUP_CONF_UPDATE_PROPS = 'USER_SIGNUP_CONF_UPDATE_PROPS';

export const USER_SIGNUP_OTP_START = 'USER_SIGNUP_OTP_START';
export const USER_SIGNUP_OTP_SUCCESS = 'USER_SIGNUP_OTP_SUCCESS';
export const USER_SIGNUP_OTP_ERROR = 'USER_SIGNUP_OTP_ERROR';
export const USER_SIGNUP_OTP_UPDATE_PROPS = 'USER_SIGNUP_OTP_UPDATE_PROPS';

export const USER_SIGNUP_AFTER_OTP_START = 'USER_SIGNUP_AFTER_OTP_START';
export const USER_SIGNUP_AFTER_OTP_SUCCESS = 'USER_SIGNUP_AFTER_OTP_SUCCESS';
export const USER_SIGNUP_AFTER_OTP_ERROR = 'USER_SIGNUP_AFTER_OTP_ERROR';
export const USER_SIGNUP_AFTER_OTP_UPDATE_PROPS =
  'USER_SIGNUP_AFTER_OTP_UPDATE_PROPS';
export const USER_SIGNUP_AFTER_OTP_RESET_STATE =
  'USER_SIGNUP_AFTER_OTP_RESET_STATE';

export const USER_SIGNIN_START = 'USER_SIGNIN_START';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_ERROR = 'USER_SIGNIN_ERROR';
export const USER_SIGNIN_UPDATE_PROPS = 'USER_SIGNIN_UPDATE_PROPS';

export const USER_SIGNIN_VERIFY_MOBILE_START =
  'USER_SIGNIN_VERIFY_MOBILE_START';
export const USER_SIGNIN_VERIFY_MOBILE_SUCCESS =
  'USER_SIGNIN_VERIFY_MOBILE_SUCCESS';
export const USER_SIGNIN_VERIFY_MOBILE_ERROR =
  'USER_SIGNIN_VERIFY_MOBILE_ERROR';
export const USER_SIGNIN_VERIFY_MOBILE_UPDATE_PROPS =
  'USER_SIGNIN_VERIFY_MOBILE_UPDATE_PROPS';

export const FORGOT_PASSWORD_START = 'FORGOT_PASSWORD_VERIFY_START';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_VERIFY_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_VERIFY_ERROR';

export const PROFILE_VIEW_START = 'PROFILE_VIEW_START';
export const PROFILE_VIEW_SUCCESS = 'PROFILE_VIEW_SUCCESS';
export const PROFILE_VIEW_ERROR = 'PROFILE_VIEW_ERROR';
export const PROFILE_VIEW_UPDATE_PROPS = 'PROFILE_VIEW_UPDATE_PROPS';

export const GET_STORIES_START = 'GET_STORIES_START';
export const GET_STORIES_SUCCESS = 'GET_STORIES_SUCCESS';
export const GET_STORIES_ERROR = 'GET_STORIES_ERROR';
export const GET_STORIES_UPDATE_PROPS = 'GET_STORIES_UPDATE_PROPS';

export const ADD_STORIES_START = 'ADD_STORIES_START';
export const ADD_STORIES_SUCCESS = 'ADD_STORIES_SUCCESS';
export const ADD_STORIES_ERROR = 'ADD_STORIES_ERROR';
export const ADD_STORIES_UPDATE_PROPS = 'ADD_STORIES_UPDATE_PROPS';

export const GET_PRODUCT_START = 'GET_PRODUCT_START';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR';
export const GET_PRODUCT_UPDATE_PROPS = 'GET_PRODUCT_UPDATE_PROPS';

export const GET_RECENT_START = 'GET_RECENT_START';
export const GET_RECENT_SUCCESS = 'GET_RECENT_SUCCESS';
export const GET_RECENT_ERROR = 'GET_RECENT_ERROR';
export const GET_RECENT_UPDATE_PROPS = 'GET_RECENT_UPDATE_PROPS';

export const GET_LOGGED_STORIES_START = 'GET_LOGGED_STORIES_START';
export const GET_LOGGED_STORIES_SUCCESS = 'GET_LOGGED_STORIES_SUCCESS';
export const GET_LOGGED_STORIES_ERROR = 'GET_LOGGED_STORIES_ERROR';
export const GET_LOGGED_STORIES_UPDATE_PROPS =
  'GET_LOGGED_STORIES_UPDATE_PROPS';

export const RESET_PASSWORD_START = 'RESET_PASSWORD_VERIFY_START';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_VERIFY_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_VERIFY_ERROR';

export const FORGOT_PASSWORD_OTP_START = 'FORGOT_PASSWORD_OTP_VERIFY_START';
export const FORGOT_PASSWORD_OTP_SUCCESS = 'FORGOT_PASSWORD_OTP_VERIFY_SUCCESS';
export const FORGOT_PASSWORD_OTP_ERROR = 'FORGOT_PASSWORD_OTP_VERIFY_ERROR';

export const FORGOT_PASSWORD_AFTER_OTP_START =
  'FORGOT_PASSWORD_AFTER_OTP_START';
export const FORGOT_PASSWORD_AFTER_OTP_SUCCESS =
  'FORGOT_PASSWORD_AFTER_OTP_SUCCESS';
export const FORGOT_PASSWORD_AFTER_OTP_ERROR =
  'FORGOT_PASSWORD_AFTER_OTP_ERROR';
export const FORGOT_PASSWORD_AFTER_OTP_PROPS_UPDATE =
  'FORGOT_PASSWORD_AFTER_OTP_PROPS_UPDATE';
export const FORGOT_PASSWORD_AFTER_OTP_RESET_STATE =
  'FORGOT_PASSWORD_AFTER_OTP_RESET_STATE';

export const CHAT_LIST_START = 'CHAT_LIST_START';
export const CHAT_LIST_SUCCESS = 'CHAT_LIST_SUCCESS';
export const CHAT_LIST_ERROR = 'CHAT_LIST_ERROR';

export const CONVERSION_LIST_START = 'CONVERSION_LIST_START';
export const CONVERSION_LIST_SUCCESS = 'CONVERSION_LIST_SUCCESS';
export const CONVERSION_LIST_ERROR = 'CONVERSION_LIST_ERROR';

export const RESET_STORE = 'RESET_STORE';

export const TOGGLE_CHAT = 'TOGGLE_CHAT';
